In [1]:
import yahoo_fin.stock_info as yf
import xlwings as xw
import pandas as pd
import datetime
import pandas_datareader.data as web
from dateutil.relativedelta import relativedelta
from multiprocessing.dummy import Pool as ThreadPool

#tickers = yf.tickers_sp500()

In [2]:
df_list = pd.DataFrame()
list_wrong = []
i = 0

def incrs_max(ticker):
    
    global i 
  
    global list_wrong
    global df_list 
    i = i + 1
    names = locals()
    end = datetime.date.today()

    start = end - relativedelta(days=360)
    #df = web.get_data_yahoo(ticker,start,end)
    
    print(i,ticker)
    try:
            
        names['df' + str(ticker)] = web.get_data_yahoo(ticker,start,end)
        
        '''
        if names['df' + str(ticker)].iloc[-1]['Adj Close'] > names['df' + str(ticker)].iloc[-2]['Adj Close']:
            j = j + 1
        else:
            k = k + 1
        '''   
        names['start_price_360' + str(ticker)] = names['df' + str(ticker)].iloc[0]['Adj Close']
        names['start_price_180' + str(ticker)] = names['df' + str(ticker)].iloc[-180]['Adj Close']
        names['start_price_90' + str(ticker)] = names['df' + str(ticker)].iloc[-90]['Adj Close']
        names['start_price_30' + str(ticker)] = names['df' + str(ticker)].iloc[-30]['Adj Close']
        names['start_price_7' + str(ticker)] = names['df' + str(ticker)].iloc[-7]['Adj Close']
        names['start_price_2' + str(ticker)] = names['df' + str(ticker)].iloc[-2]['Adj Close']
        names['end_price' + str(ticker)] = names['df' + str(ticker)].iloc[-1]['Adj Close']
        
        names['increase_2' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_2' + str(ticker)] - 1
        names['increase_7' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_7' + str(ticker)] - 1
        names['increase_30' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_30' + str(ticker)] - 1
        names['increase_90' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_90' + str(ticker)] - 1
        names['increase_180' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_180' + str(ticker)] - 1
        names['increase_360' + str(ticker)] = names['end_price' + str(ticker)]/names['start_price_360' + str(ticker)] - 1
                               
                
        df_list = df_list.append(pd.DataFrame({'ticker':[ticker],\
                                        
                                         'start':names['df' + str(ticker)].index[0],\
                                         'end':names['df' + str(ticker)].index[-1],\
                                         #'start_price':names['start_price' + str(ticker)],\
                                         'end_price':names['end_price' + str(ticker)],\
                                         'start_price_7':names['start_price_7' + str(ticker)],\
                                         'start_price_30':names['start_price_30' + str(ticker)],\
                                         'start_price_90':names['start_price_90' + str(ticker)],\
                                         'start_price_180':names['start_price_180' + str(ticker)],\
                                         'start_price_360':names['start_price_360' + str(ticker)],\
                                               
                                         'increase_2':names['increase_2' + str(ticker)],\
                                         'increase_7':names['increase_7' + str(ticker)],\
                                         'increase_30':names['increase_30' + str(ticker)],\
                                         'increase_90':names['increase_90' + str(ticker)],\
                                         'increase_180':names['increase_180' + str(ticker)],\
                                         'increase_360':names['increase_360' + str(ticker)],

                                         }),ignore_index=True,sort=False) 
            
        
    except:
        print(ticker,'.....................wrong.....................')
        list_wrong.append(ticker)

In [3]:
#list_wrong = []
#tickers = list_tickers 
tickers = yf.tickers_sp500()

#tickers = ['JPM']
#tickers = unionset
#tickers1 = unionset[0:4]
df_list = df_list.drop(index = df_list.index)
pool = ThreadPool()
pool.map(incrs_max, tickers)
pool.close()
pool.join()

1 A
2 AMP
3 BKNG
4 CL
5 BKR
6 CLX
7 AMT
8 AAL
9 CMA
10 BLK
11 AAP
12 CMCSA
13 AMZN
14 CME
15 BMY
16 AAPL
17 CMG
18 ANET
19 ABBV
20 BR
21 CMI
22 ANSS
23 CMS
24 AON
25 BRK-B
26 ABC
27 AOS
28 CNC
29 BRO
30 APA
31 CNP
32 BSX
33 ABMD
34 APD
35 BWA
36 ABT
37 APH
38 BXP
39 COF
40 C
41 ACN
42 COO
43 APTV
44 CAG
45 ADBE
46 COP
47 CAH
48 ADI
49 ARE
50 COST
51 ADM
52 CARR
53 CPB
54 ATO
55 ADP
56 CAT
57 ATVI
58 CPRT
59 ADSK
60 CB
61 AVB
62 CPT
63 AEE
64 CBOE
65 CBRE
66 AVGO
67 CRL
68 AEP
69 CRM
70 AVY
71 AES
72 CCI
73 CSCO
74 AFL
75 AWK
76 CCL
77 AIG
78 CSX
79 CDAY
80 AIZ
81 CDNS
82 AXP
83 CTAS
84 AJG
85 AZO
86 CDW
87 CTLT
88 AKAM
89 BA
90 CE
91 CTRA
92 BAC
93 CEG
94 ALB
95 CTSH
96 BALL
CEG .....................wrong.....................
97 CF
98 CTVA
99 ALGN
100 BAX
101 CFG
102 ALK
103 CTXS
104 BBWI
105 CHD
106 ALL
107 CVS
108 BBY
109 CHRW
110 ALLE
111 BDX
112 CVX
113 CHTR
114 AMAT
115 BEN
116 CZR
117 CI
118 BF-B
119 D
120 AMCR
121 CINF
122 BIIB
123 AMD
124 DD
125 DAL
126 BIO
127 AME
128 BK
129 ENPH
130 DE
131 AMGN
132 EOG
133 FRC
134 DFS
135 HRL
136 FRT
137 DG
138 EPAM
139 HSIC
140 FTNT
141 EQIX
142 DGX
143 HST
144 EQR
145 FTV
146 DHI
147 GD
148 ES
149 HSY
150 DHR
151 GE
152 HUM
153 ESS
154 DIS
155 GILD
156 HWM
157 ETN
158 DISH
159 GIS
160 IBM
161 ETR
162 DLR
163 ICE
164 GL
165 ETSY
166 DLTR
167 EVRG
168 IDXX
169 DOV
170 GLW
171 IEX
172 EW
173 GM
174 DOW
175 IFF
176 GNRC
177 EXC
178 DPZ
179 GOOG
180 DRE
181 ILMN
182 EXPD
183 GOOGL
184 INCY
185 186GPC
 DRI
187 EXPE
188 INTC
189 DTE
190 EXR
191 GPN
192 INTU
193 DUK
194 F
195 GRMN
196 IP
197 DVA
198 FANG
199 GS
200 IPG
201 DVN
202 FAST
203 GWW
204 IQV
205 DXC
206 FBHS
207 IR
208 HAL
209 DXCM
210 FCX
211 IRM
212 HAS
213 EA
214 FDS
215 ISRG
216 HBAN
217 EBAY
218 IT
219 FDX
220 HCA
221 ECL
222 ITW
223 FE
224 HD
225 IVZ
226 ED
227 FFIV
228 J
229 HES
230 FIS
231 EFX
232 JBHT
233 HIG
234 FISV
235 EIX
236 HII
237 JCI
238 FITB
239 EL
240 HLT
241 FLT
242 JKHY
243 ELV
244 HOLX
245 FMC
246 JNJ
247 EMN
248 HON
249 FOX
250 JNPR
251 EMR
252 FOXA
253 HPE
254 JPM
255 HPQ
256 KDP
257 MAR
258 K
259 MAS
260 KEY
261 MTD
262 ORLY
263 MU
264 MCD
265 KEYS
266 OTIS
267 MCHP
268 KHC
269 OXY
270 NCLH
271 KIM
272 MCK
273 NDAQ
274 PARA
275 KLAC
276 MCO
277 NDSN
278 PAYC
279 KMB
280 MDLZ
281 PAYX
282 NEE
283 KMI
284 MDT
285 PCAR
286 NEM
287 KMX
288 MET
289 PEAK
290 KO
291 NFLX
292 META
293 PEG
294 KR
295 NI
296 MGM
297 NKE
298 PENN299
 L
300 MHK
301 PEP
302 NLOK
303 MKC
304 LDOS
305 PFE
306 NLSN
307 LEN
308 MKTX
309 NOC
310 PFG
311 MLM
312 LH
313 NOW
314 PG
315 MMC
316 LHX
317 NRG
318 PGR
319 MMM
320 LIN
321 NSC
322 PH
323 MNST
324 LKQ
325 NTAP
326 MO
327 PHM
328 NTRS
329 LLY
330 MOH
331 PKG
332 NUE
333 LMT
334 MOS
335 LNC
336 NVDA
337 PKI
338 LNT
339 MPC
340 PLD
341 NVR
342 LOW
343 MPWR
344 PM
345 NWL
346 LRCX
347 MRK
348 PNC
349 NWS
350 LUMN
351 MRNA
352 PNR
353 NWSA
354 LUV
355 MRO
356 PNW
357 NXPI
358 LVS
359 MS
360 POOL
361 O
362 LW
363 MSCI
364 PPG
365 LYB
366 ODFL
367 MSFT
368 LYV
369 OGN
370 PPL
371 MSI
372 MA
373 OKE
374 PRU
375 MTB
376 OMC
377 MAA
378 PSA
379 PWR
380 ON
381 PSX
382 MTCH
383 PXD
384 ORCL
385 PTC
386 SO
387 PVH
388 TSN
389 PYPL
390 SPG
391 TT
392 WDC
393 QCOM
394 SPGI
395 TTWO
396 WEC
397 QRVO
398 SRE
399 WELL
400 RCL
401 TWTR
402 STE
403 WFC
404 TXN
405 RE
406 WHR
407 TXT
408 STT
409 REG
410 WM
411 412 STXTYL

413 REGN
414 WMB
415 UAL
416 STZ
417 RF
418 WMT
419 UDR
420 RHI
421 SWK
422 WRB
423 UHS
424 RJF
425 SWKS
426 WRK
427 ULTA
428 RL
429 WST
430 SYF
431 UNH
432 RMD
433 SYK
434 WTW
435 UNP
436 ROK
437 SYY
438 WY
439 UPS
440 ROL
441 T
442 WYNN
443 URI
444 ROP
445 TAP
446 USB
447 ROST
448 XEL
449 TDG
450 V
451 RSG
452 XOM
453 VFC
454 RTX
455 TDY
456 XRAY
457 VICI
458 TECH
459460 XYL
 SBAC
461 VLO
462 TEL
463 YUM
464 SBNY
465 VMC
466 TER
467 ZBH
468 SBUX
469 VNO
470 TFC
471 ZBRA
472 SCHW
473 VRSK
474 ZION
475 TFX
476 VRSN
477 SEDG
478 TGT
479 ZTS
480 VRTX
481 SEE
482 TJX
483 VTR
484 SHW
485 TMO
486 VTRS
487 SIVB
488 TMUS
489 SJM
490 TPR
491 VZ
492 TRMB
493 WAB
494 SLB
495 TROW
496 WAT
497 SNA
498 TRV
499 WBA
500 SNPS
501 TSCO
502 WBD
503 TSLA

In [5]:
list_wrong

['CEG']

In [6]:
df_list

,ticker,start,end,end_price,start_price_7,start_price_30,start_price_90,start_price_180,start_price_360,increase_2,increase_7,increase_30,increase_90,increase_180,increase_360
0,BKNG,2021-09-20,2022-09-14,1967.380005,1814.849976,1966.479980,2194.229980,2386.909912,2340.739990,0.024250,0.084046,0.000458,-0.103385,-0.175763,-0.159505
1,CL,2021-09-20,2022-09-14,76.059998,77.769997,81.430000,76.374184,83.007614,74.409691,0.008352,-0.021988,-0.065946,-0.004114,-0.083699,0.022179
2,AMP,2021-09-20,2022-09-14,277.959991,268.489990,268.811951,265.367950,301.780182,252.115952,0.000864,0.035271,0.034031,0.047451,-0.078932,0.102509
3,A,2021-09-20,2022-09-14,133.250000,129.300003,134.559998,120.865921,158.440781,170.332214,-0.002172,0.030549,-0.009735,0.102461,-0.158992,-0.217705
4,CLX,2021-09-20,2022-09-14,141.630005,142.710007,144.570007,152.710739,168.148361,159.999100,-0.016458,-0.007568,-0.020336,-0.072560,-0.157708,-0.114807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,WBA,2021-09-20,2022-09-14,34.770000,35.320000,39.189999,43.990002,51.430000,48.400002,0.000864,-0.015572,-0.112784,-0.209593,-0.323935,-0.281612
498,SNPS,2021-09-20,2022-09-14,323.369995,326.829987,370.839996,274.709991,372.149994,321.299988,-0.000742,-0.010587,-0.128007,0.177132,-0.131076,0.006443
499,TSCO,2021-09-20,2022-09-14,189.009995,188.039993,190.919998,202.559998,231.169998,205.589996,-0.023759,0.005158,-0.010004,-0.066894,-0.182377,-0.080646
500,WBD,2021-09-20,2022-09-14,12.710000,12.630000,16.709999,17.750000,24.330000,26.010000,-0.018533,0.006334,-0.239378,-0.283944,-0.477600,-0.511342
501,TSLA,2021-09-20,2022-09-14,302.609985,274.420013,307.396667,288.549988,362.823334,243.389999,0.035874,0.102726,-0.015572,0.048726,-0.165958,0.243313

In [7]:
j = 0
while len(list_wrong) > 1 and j < 3:
    tickers = list_wrong
    list_wrong = []
    
    pool = ThreadPool()
    pool.map(incrs_max, tickers)
    pool.close()
    pool.join()
    j = j + 1
    '''
   for ticker in 
    incrs_max(ticker)
    #tickers = ['JPM']
    #tickers = unionset
    #tickers1 = unionset[0:4]
    #df_list = df_list.drop(index = df_list.index)
    '''

In [10]:
incr_pct_2 = (df_list[df_list['increase_2']>0]['ticker'].count())/(df_list['ticker'].count())
incr_pct_7 = (df_list[df_list['increase_7']>0]['ticker'].count())/(df_list['ticker'].count())
incr_pct_30 = (df_list[df_list['increase_30']>0]['ticker'].count())/(df_list['ticker'].count())
incr_pct_90 = (df_list[df_list['increase_90']>0]['ticker'].count())/(df_list['ticker'].count())
incr_pct_180 = (df_list[df_list['increase_180']>0]['ticker'].count())/(df_list['ticker'].count())
incr_pct_360 = (df_list[df_list['increase_360']>0]['ticker'].count())/(df_list['ticker'].count())

df_top10_7 = df_list.sort_values(by='increase_7',axis=0,ascending=False).head(10).loc[:,['ticker','end','end_price','increase_7','increase_30','increase_90','increase_180','increase_360']]
df_top10_30 = df_list.sort_values(by='increase_30',axis=0,ascending=False).head(10).loc[:,['ticker','end','end_price','increase_7','increase_30','increase_90','increase_180','increase_360']]
df_top10_90 = df_list.sort_values(by='increase_90',axis=0,ascending=False).head(10).loc[:,['ticker','end','end_price','increase_7','increase_30','increase_90','increase_180','increase_360']]
df_top10_180 = df_list.sort_values(by='increase_180',axis=0,ascending=False).head(10).loc[:,['ticker','end','end_price','increase_7','increase_30','increase_90','increase_180','increase_360']]
df_top10_360 = df_list.sort_values(by='increase_360',axis=0,ascending=False).head(10).loc[:,['ticker','end','end_price','increase_7','increase_30','increase_90','increase_180','increase_360']]

wb = xw.Book('C:/Users/zty1979/Documents/美股/dashboard.xlsx')
sht_list = wb.sheets['list']
sht_list.range('D3').expand().value = df_top10_7
sht_list.range('D18').expand().value = df_top10_30
sht_list.range('D33').expand().value = df_top10_90
sht_list.range('D48').expand().value = df_top10_180
sht_list.range('D63').expand().value = df_top10_360

sht_list.range('F1').value = incr_pct_2
sht_list.range('F15').value = incr_pct_7
sht_list.range('F30').value = incr_pct_30
sht_list.range('F45').value = incr_pct_90
sht_list.range('F60').value = incr_pct_180
sht_list.range('F75').value = incr_pct_360

In [9]:
df_list[df_list['ticker']=='GE']

,ticker,start,end,end_price,start_price_7,start_price_30,start_price_90,start_price_180,start_price_360,increase_2,increase_7,increase_30,increase_90,increase_180,increase_360
149,GE,2021-09-20,2022-09-14,70.029999,72.160004,74.739998,78.230003,95.300003,99.645195,-0.011434,-0.029518,-0.063018,-0.104819,-0.265163,-0.297206

In [19]:
len(list_wrong)

1